# Generated by Django 2.0.13 on 2019-07-29 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('horas', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('votes2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Choice_aa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Conversa_ML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversa', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Dbd_Dados_Bot_Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBD_BOT_ID', models.TextField()),
                ('DBD_BOT_TIME', models.TextField()),
                ('DBD_BOT_MESSAGING_SENDER_ID', models.TextField()),
                ('DBD_BOT_MESSAGING_RECIPIENT_ID', models.TextField()),
                ('DBD_BOT_MESSAGING_TIME', models.TextField()),
                ('DBD_BOT_MESSAGING_DELIVERY_MIDS', models.TextField()),
                ('DBD_BOT_MESSAGING_DELIVERY_WATERMARK', models.TextField()),
                ('DBD_BOT_MESSAGING_DELIVERY_SEQ', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dbr_Dados_Bot_Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBR_BOT_ID', models.TextField()),
                ('DBR_BOT_TIME', models.TextField()),
                ('DBR_BOT_MESSAGING_SENDER_ID', models.TextField()),
                ('DBR_BOT_MESSAGING_RECIPIENT_ID', models.TextField()),
                ('DBR_BOT_MESSAGING_TIME', models.TextField()),
                ('DBR_BOT_MESSAGING_READ_WATERMARK', models.TextField()),
                ('DBR_BOT_MESSAGING_READ_SEQ', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Drb_Dados_Resposta_Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DRB_BOT_ID', models.TextField()),
                ('DRB_BOT_TIME', models.TextField()),
                ('DRB_BOT_MESSAGING_SENDER_ID', models.TextField()),
                ('DRB_BOT_MESSAGING_RECIPIENT_ID', models.TextField()),
                ('DRB_BOT_MESSAGING_TIME', models.TextField()),
                ('DRB_BOT_MESSAGING_MESSAGE_IS_ECHO', models.TextField()),
                ('DRB_BOT_MESSAGING_MESSAGE_APP_ID', models.TextField()),
                ('DRB_BOT_MESSAGING_MESSAGE_MID', models.TextField()),
                ('DRB_BOT_MESSAGING_MESSAGE_SEQ', models.TextField()),
                ('DRB_BOT_MESSAGING_MESSAGE_TEXT', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dsc_Dados_Conversa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DSC_BOT_ID', models.TextField()),
                ('DSC_BOT_TIME', models.TextField()),
                ('DSC_BOT_MESSAGING_SENDER_ID', models.TextField()),
                ('DSC_BOT_MESSAGING_RECIPIENT_ID', models.TextField()),
                ('DSC_BOT_MESSAGING_TIME', models.TextField()),
                ('DSC_BOT_MESSAGING_MESSAGE_MID', models.TextField()),
                ('DSC_BOT_MESSAGING_MESSAGE_SEQ', models.TextField()),
                ('DSC_BOT_MESSAGING_MESSAGE_TEXT', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionalidades_bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lista_Horas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MDC_Mineracao_Dados_Cassandra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.TextField()),
                ('json_dados', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('status_acesso', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_cargo_hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.CharField(max_length=15, null=True)),
                ('periodo_entrada', models.CharField(max_length=10, null=True)),
                ('hora_almoco', models.CharField(max_length=15, null=True)),
                ('periodo_almoco', models.CharField(max_length=10, null=True)),
                ('id_cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mybot.Cargo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=None, null=True)),
                ('ativo', models.IntegerField(null=True)),
                ('id_funcionalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.Funcionalidades_bot')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='funcionalidades_bot',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.Role'),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='id_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mybot.Role'),
        ),
        migrations.AddField(
            model_name='choice_aa',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.Question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.Question'),
        ),
    ]
