# Generated by Django 2.0.13 on 2019-06-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0002_choice_aa'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes2',
            field=models.IntegerField(default=0),
        ),
    ]
