# Generated by Django 2.0.13 on 2019-06-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0003_choice_votes2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
