# Generated by Django 2.0.13 on 2019-06-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0004_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
