# Generated by Django 2.0.13 on 2019-06-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0005_auto_20190622_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
