# Generated by Django 2.0.13 on 2019-06-22 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0006_auto_20190622_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='id_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mybot.Role'),
        ),
    ]
