# Generated by Django 2.0.13 on 2019-06-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0007_auto_20190622_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='nome',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
