# Generated by Django 2.0.13 on 2019-06-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0008_colaboradores_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='status_acesso',
            field=models.IntegerField(null=True),
        ),
    ]
