# Generated by Django 2.0.13 on 2019-06-27 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0010_funcionalidades_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=0)),
                ('id_funcionalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.Funcionalidades_bot')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.Usuario')),
            ],
        ),
    ]
