# Generated by Django 2.0.13 on 2019-07-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0011_usuario_funcao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_Horas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.CharField(max_length=200)),
            ],
        ),
    ]
