# Generated by Django 2.0.13 on 2019-07-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0012_lista_horas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa_ML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversa', models.CharField(max_length=1000)),
            ],
        ),
    ]
