# Generated by Django 2.0.13 on 2019-07-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0013_conversa_ml'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDC_Mineracao_Dados_Cassandra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.TextField()),
                ('json_dados', models.TextField()),
            ],
        ),
    ]
