# Generated by Django 2.0.13 on 2019-07-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0014_mdc_mineracao_dados_cassandra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdc_mineracao_dados_cassandra',
            name='id',
        ),
        migrations.AlterField(
            model_name='mdc_mineracao_dados_cassandra',
            name='json_dados',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
