# Generated by Django 2.0.13 on 2019-07-14 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0015_auto_20190714_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MDC_Mineracao_Dados_Cassandra',
        ),
    ]
