# Generated by Django 2.0.13 on 2019-07-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0017_mdc_mineracao_dados_cassandra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MDC_Mineracao_Dados_Cassandra',
        ),
    ]
