# Generated by Django 2.0.13 on 2019-07-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0019_mdc_mineracao_dados_cassandra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dbd_Dados_Bot_Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBD_BOT_ID', models.BigIntegerField()),
                ('DBD_BOT_MESSAGING_SENDER_ID', models.TextField()),
                ('DBD_BOT_MESSAGING_RECIPIENT_ID', models.TextField()),
                ('DBD_BOT_MESSAGING_DELIVERY_MIDS', models.TextField()),
                ('DBD_BOT_MESSAGING_DELIVERY_WATERMARK', models.TextField()),
                ('DBD_BOT_MESSAGING_DELIVERY_SEQ', models.TextField()),
            ],
        ),
    ]
