# Generated by Django 2.0.13 on 2019-07-18 01:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0020_dbd_dados_bot_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dbr_Dados_Bot_Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBR_BOT_ID', models.TextField()),
                ('DBR_BOT_TIME', models.TextField()),
                ('DBR_BOT_MESSAGING_SENDER_ID', models.TextField()),
                ('DBR_BOT_MESSAGING_RECIPIENT_ID', models.TextField()),
                ('DBR_BOT_MESSAGING_TIME', models.TextField()),
                ('DBR_BOT_MESSAGING_READ_WATERMARK', models.TextField()),
                ('DBR_BOT_MESSAGING_READ_SEQ', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Drb_Dados_Resposta_Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DRB_BOT_ID', models.TextField()),
                ('DRB_BOT_TIME', models.TextField()),
                ('DRB_BOT_MESSAGING_SENDER_ID', models.TextField()),
                ('DRB_BOT_MESSAGING_RECIPIENT_ID', models.TextField()),
                ('DRB_BOT_MESSAGING_TIME', models.TextField()),
                ('DRB_BOT_MESSAGING_MESSAGE_IS_ECHO', models.TextField()),
                ('DRB_BOT_MESSAGING_MESSAGE_APP_ID', models.TextField()),
                ('DRB_BOT_MESSAGING_MESSAGE_MID', models.TextField()),
                ('DRB_BOT_MESSAGING_MESSAGE_SEQ', models.TextField()),
                ('DRB_BOT_MESSAGING_MESSAGE_TEXT', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dsc_Dados_Conversa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DSC_BOT_TIME', models.TextField()),
                ('DSC_BOT_MESSAGING_SENDER_ID', models.TextField()),
                ('DSC_BOT_MESSAGING_RECIPIENT_ID', models.TextField()),
                ('DSC_BOT_MESSAGING_TIME', models.TextField()),
                ('DSC_BOT_MESSAGING_MESSAGE_MID', models.TextField()),
                ('DSC_BOT_MESSAGING_MESSAGE_SEQ', models.TextField()),
                ('DSC_BOT_MESSAGING_MESSAGE_TEXT', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='dbd_dados_bot_delivery',
            name='DBD_BOT_MESSAGING_TIME',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dbd_dados_bot_delivery',
            name='DBD_BOT_TIME',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dbd_dados_bot_delivery',
            name='DBD_BOT_ID',
            field=models.TextField(),
        ),
    ]
