# Generated by Django 2.0.13 on 2019-07-18 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0021_auto_20190717_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsc_dados_conversa',
            name='DSC_BOT_ID',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
